apiVersion: apps.kubermatic.k8c.io/v1
kind: ApplicationDefinition
metadata:
  name: service-engine
spec:
  description: COPA-DATA Service Engine
  method: helm
  versions:
    - template:
        source:
          helm:
            chartName: Service-Engine
            chartVersion: 14.0.0
            url: https://github.com/FLECS-Technologies/apps-com.copadata.service-engine-bi/tree/main/k8s/helm
      version: 14.0.0
