apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceEngine.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.serviceEngine.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceEngine.name }}
    spec:
      {{ if .Values.serviceEngine.hostName }}
      hostname: {{ .Values.serviceEngine.hostName }}
      {{ end }}
      containers:
        - name: {{ .Values.serviceEngine.name }}
          image: {{ .Values.serviceEngine.image }}:{{ .Values.version.tag }}
          env:
            - name: RUNTIME_LICENSING_SERIAL0
              value: {{ .Values.licensing.serviceEngine.serial }}
            - name: RUNTIME_LICENSING_SERIAL0_LOCATION
              value: {{ .Values.licensing.serviceEngine.server }}
            - name: PROCESSGATEWAY_LICENSING_SERIAL0
              value: {{ .Values.licensing.processGateway.serial }}
            - name: PROCESSGATEWAY_LICENSING_SERIAL0_LOCATION
              value: {{ .Values.licensing.processGateway.server }}
            - name: LOGIC_LICENSING_SERIAL0
              value: {{ .Values.licensing.logicService.serial }}
            - name: LOGIC_LICENSING_SERIAL0_LOCATION
              value: {{ .Values.licensing.logicService.server }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8}}
      {{ end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8}}
      {{- end }}
      {{- with .Values.nodeAffinity }}
      affinity:
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
      {{- end }}